import '../styles/globals.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'
import { trpc } from '../utils/trpc'

function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>tRPC POC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  )
}

export default trpc.withTRPC(App)
